version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - PHP_ERROR_REPORTING=E_ALL

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_mvc
      MYSQL_USER: aaa
      MYSQL_PASSWORD: ''
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: 